name: .NET Core CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "walletapi-heroku"
          heroku_email: "nanyankah@gmail.com"
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore WalletAPI.Services.Test/WalletAPI.Services.Test.csproj
    - name: Build
      run: dotnet build --no-restore WalletAPI.Services.Test/WalletAPI.Services.Test.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal WalletAPI.Services.Test/WalletAPI.Services.Test.csproj
